# Generated by Django 5.2.16 on 2026-07-27 05:46

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_seed_canonical_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En proceso'), ('ON_HOLD', 'En espera'), ('COMPLETED', 'Completado'), ('DISMISSED', 'Desestimado')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogs.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ticket_snapshots', to='catalogs.department')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.FileField(max_length=500, unique=True, upload_to=tickets.models.ticket_attachment_upload_to)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_attachments',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('author_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comment_snapshots', to='catalogs.role')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_comments',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_history_entries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_history',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TicketHistoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='tickets.tickethistory')),
            ],
            options={
                'db_table': 'ticket_history_changes',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='tickets_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'created_at'], name='tickets_priority_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester', 'created_at'], name='tickets_requester_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_technician', 'status'], name='tickets_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', 'status'], name='tickets_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester_department', 'created_at'], name='tickets_department_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['due_date', 'status'], name='tickets_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['taken_at'], name='tickets_taken_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['closed_at'], name='tickets_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['updated_at'], name='tickets_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='tickets_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='tickets_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'DISMISSED'])), name='tickets_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='tickets_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('taken_at__isnull', True), ('taken_at__gte', models.F('created_at')), _connector='OR'), name='tickets_taken_after_created'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('created_at')), _connector='OR'), name='tickets_closed_after_created'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status__in', ('COMPLETED', 'DISMISSED'))), models.Q(('closed_at__isnull', True), ('status__in', ('OPEN', 'IN_PROGRESS', 'ON_HOLD'))), _connector='OR'), name='tickets_closed_status_consistent'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', 'created_at'], name='attachments_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='attach_uploader_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(('file_name', ''), _negated=True), name='attachments_file_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type', ''), _negated=True), name='attachments_mime_type_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='attachments_size_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'created_at'], name='comments_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['author', 'created_at'], name='comments_author_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketcomment',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='ticket_comments_message_not_empty'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['ticket', 'created_at'], name='history_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['actor', 'created_at'], name='history_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['action_code', 'created_at'], name='history_action_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickethistory',
            constraint=models.CheckConstraint(condition=models.Q(('action_code', ''), _negated=True), name='ticket_history_action_not_empty'),
        ),
        migrations.AddIndex(
            model_name='tickethistorychange',
            index=models.Index(fields=['history', 'field_code'], name='history_changes_field_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickethistorychange',
            constraint=models.CheckConstraint(condition=models.Q(('field_code', ''), _negated=True), name='history_changes_field_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tickethistorychange',
            constraint=models.CheckConstraint(condition=models.Q(('old_value__isnull', False), ('new_value__isnull', False), _connector='OR'), name='history_changes_has_value'),
        ),
    ]
