# Generated by Django 5.2.16 on 2026-07-28 03:09

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_seed_approved_catalogs'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tickethistorychange',
            name='history_changes_field_idx',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', django.db.models.functions.comparison.Cast(models.F('created_at'), output_field=models.DateField())), _connector='OR'), name='tickets_due_on_after_created'),
        ),
        migrations.AddConstraint(
            model_name='tickethistorychange',
            constraint=models.UniqueConstraint(fields=('history', 'field_code'), name='history_changes_history_field_uniq'),
        ),
    ]
