# Generated by Django 5.2.16 on 2026-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['active', 'name'], name='categories_active_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='categories_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['active', 'name'], name='departments_active_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='departments_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('TECHNICIAN', 'Técnico'), ('EMPLOYEE', 'Empleado')], db_collation='utf8mb4_bin', max_length=32, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ('code', 'id'),
                'indexes': [models.Index(fields=['active', 'code'], name='roles_active_code_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['ADMINISTRATOR', 'TECHNICIAN', 'EMPLOYEE'])), name='roles_code_canonical_ck')],
            },
        ),
    ]
